# Generated by Django 4.0.2 on 2022-03-30 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_title', models.CharField(max_length=50, verbose_name='Долгосрочная цель')),
                ('goal_description', models.CharField(max_length=250, verbose_name='Описание долгосрочной цели')),
                ('subtasks', models.CharField(max_length=250, verbose_name='Подзадачи')),
                ('date', models.DateField(verbose_name='Дата добавления цели')),
                ('deadline', models.DateField(verbose_name='Срок выполнения цели')),
                ('complete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'order_with_respect_to': 'user',
            },
        ),
    ]
